bimeh/urls.py
from django.contrib import admin
from django.urls import path,include
from main import views

app_name ='bimeh'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('main/',include('main.urls'))
]

main/urls.py
from django.urls import path
from main import views

app_name ='main'
urlpatterns=[
  
    path('workers_list/',views.workers_list,name="workers_list"),
    path('workhouses_list/',views.workhouses_list,name='workhouses_list'),
    path('month_list/',views.month_list,name="month_list"),
    path('details_list/<int:list_id>',views.details_list,name="details_list"),
    path('export_kar/',views.export_workhouse_data, name='export_workhouse_data'),
    path('export_worker/',views.export_workers_data, name='export_workers_data'),
    path('import_workhouses/',views.import_workhouses_data, name='import_workhouses_data'),
    path('import_workers/',views.import_workers_data, name='import_workers_data'),
    path('workhouse_reg/',views.workhouse_reg, name='workhouse_reg'),
    path('workers_reg/',views.workers_reg, name='workers_reg'),
    path('list_reg/',views.list_reg, name='list_reg'),
    path('details_reg/',views.details_reg, name='details_reg'),

]

main/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import User
from main.choices import *
from django.db.models import F,BigIntegerField,ExpressionWrapper
from django.utils.translation import gettext_lazy as _


class AnnotationManager(models.Manager):

    def __init__(self, **kwargs):
        super().__init__()
        self.annotations = kwargs

    def get_queryset(self):
        return super().get_queryset().annotate(**self.annotations)



class WorkHouse(models.Model):

    class Meta:

        verbose_name=' ثبت کارگاه '
        verbose_name_plural=' ثبت کارگاه '


    Code=models.CharField('کد کارگاه',max_length=10,
                            validators=[RegexValidator(r'^\d{1,10}$',
                            message='فقط عدد وارد شود')])
    ContractRow=models.CharField('ردیف پیمان',max_length=3,
                            validators=[RegexValidator(r'^\d{1,10}$',
                            message='فقط عدد وارد شود')])
    Name=models.CharField('نام کارگاه',max_length=100)
    Client=models.CharField('نام کارفرما',max_length=100)
    Address=models.CharField('آدرس کارگاه',max_length=100)
    Ratio=models.CharField('نرخ حق بیمه',max_length=2,
                            validators=[RegexValidator(r'^\d{1,10}$',
                            message='فقط عدد وارد شود')])
    
    

    def __str__(self):
        return 'نام کارگاه :{}- کد کارگاه :{} - ردیف پیمان: {}'.format(self.Name,
                            self.Code,self.ContractRow)

class Workers(models.Model):

    class Meta:

        verbose_name='کارکنان'
        verbose_name_plural='کارکنان'


    # city_chioce_dict={city:value for value,city in city_choice}

    BimehNum=models.CharField('شماره بیمه',max_length=10,
                            validators=[RegexValidator(r'^\d{1,10}$',
                            message='فقط عدد وارد شود')])

    PersoneliNum=models.CharField('شماره پرسنلی',max_length=10,
                            validators=[RegexValidator(r'^\d{1,10}$',
                            message='فقط عدد وارد شود')])

    LastName=models.CharField('نام خانوادگی',max_length=100)

    FirstName=models.CharField('نام ',max_length=100)

    DadName=models.CharField('نام پدر',max_length=100)

    NationNum=models.CharField('کد ملی ',max_length=10,
                            validators=[RegexValidator(r'^\d{1,10}$',
                            message='فقط عدد وارد شود')])
        
    IdNum=models.CharField('شماره شناسنامه',max_length=15,
                            validators=[RegexValidator(r'^\d{1,10}$',
                            message='فقط عدد وارد شود')])

    IdPlace=models.CharField('محل صدور ',choices=city_choice,max_length=100)

    BirthPlace=models.CharField('محل تولد ',choices=city_choice,max_length=100)

    RegisterDate=models.CharField('تاریخ صدور ',null=True,max_length=8)

    BirthDate=models.CharField('تاریخ تولد ',null=True,max_length=8)



    Sex=models.CharField('جنسیت ',choices=sex_choice,max_length=3)

    Nationality=models.CharField('ملیت ',choices=nat_choice,max_length=10)

    Job=models.CharField('شغل',choices=job_choice,max_length=10)


    

    def __str__(self):
        return ' {} {} فرزند:{} شماره بیمه:{} شغل:{} '.format(self.FirstName ,
                    self.LastName,self.DadName,self.BimehNum,self.Job)


class MonthList(models.Model):

    class Meta:

        verbose_name='لیست ماهانه'
        verbose_name_plural='لیست ماهانه'

    
    workhouse=models.ForeignKey('WorkHouse',on_delete=models.CASCADE,verbose_name='کارگاه ')
    year=models.CharField('سال',max_length=2,null=True,
                                validators=[RegexValidator(r'^\d{1,10}$',
                                message='فقط عدد وارد شود')])
    month=models.CharField('ماه',max_length=2,null=True,
                                validators=[RegexValidator(r'^\d{1,10}$',
                                message='فقط عدد وارد شود')])
    
    # models.constants
    # list_type=0
    # list_number=0
    # list_description=''
    # porsantaj_ratio=0
    # hard_ratio=0

    def __str__(self):
        return 'کارگاه : {}  لیست سال : {}  ماه :{} '.format(self.workhouse.Name,self.year,self.month)

class DetailsList(models.Model):

    
    class Meta:

        verbose_name=' جزئیات لیست '
        verbose_name_plural=' جزئیات لیست '

    month_list=models.ForeignKey('MonthList',on_delete=models.CASCADE,verbose_name='لیست ماهانه')
    worker=models.ForeignKey('Workers',on_delete=models.CASCADE,verbose_name=' نام کارگر')
    working_days=models.SmallIntegerField('تعداد روز کارکرد')
    daily_wage=models.BigIntegerField('دستمزد روزانه')
    advantage=models.BigIntegerField('مزایای ماهانه')
    start_date=models.CharField('تاریخ شروع به کار ' ,null=True, max_length=8 )
    end_date=models.CharField('تاریخ پایان به کار ',null=True,max_length=8)



    _monthly_wage=None

    objects = AnnotationManager(

        
        monthly_wage=ExpressionWrapper(F('working_days') * F('daily_wage') , output_field=BigIntegerField())
        

    )

    def __str__(self):
        return '{} {} {} '.format(self.worker.FirstName,self.worker.LastName,self.month_list)

main/forms.py
from django import forms 
# from django.forms import ModelForm
from main.models import WorkHouse,Workers,MonthList,DetailsList


class WorkhouseForm(forms.ModelForm):
    class Meta:
        model=WorkHouse

        # fields=['Name']
        exclude=[]

class WorkersForm(forms.ModelForm):
    class Meta:
        model=Workers
        exclude=[]

class MonthlistForm(forms.ModelForm):
    class Meta:
        model=MonthList
        exclude=[]

class DetailsForm(forms.ModelForm):
    class Meta:
        model=DetailsList
        exclude=[]

main/views.py

from django.shortcuts import render,get_object_or_404
from main.models import WorkHouse,Workers,DetailsList,MonthList

import csv
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django.db.models import Count,Sum
from django.db.models import F,BigIntegerField,ExpressionWrapper,CharField,Value
from main.choices import city_choice,job_choice
from main.forms import WorkhouseForm,WorkersForm,MonthlistForm,DetailsForm
import codecs
from main import iransystem

def reverse(s):
    return s[::-1]

codecs.register(lambda e: iransystem.getregentry())

def home(request):
    return render(request,"main/home.html")


def workers_list(request):

    workers=Workers.objects.all()

    context={
        'workers':workers
    }

    return render(request,"main/workers_list.html",context)

def workhouses_list(request):
    workhouses=WorkHouse.objects.all()

    context={
        'workhouses':workhouses
    }

    return render(request,'main/workhouse_list.html',context)

def month_list(request):

    months_list=MonthList.objects.all()

    context={

        'months_list':months_list


    }
    
    return render(request,'main/month_list.html',context)

def details_list(request,list_id):

    # records=get_object_or_404(DetailsList,pk=list_id) 
    records= DetailsList.objects.filter(month_list__pk=list_id)

    context={

        'records': records

    }    

    return render (request,'main/details_list.html',context)



def export_workhouse_data(request):

    #this section for .csv files

    response = HttpResponse(content_type='text/csv ;charset=iransystem')
    response['Content-Disposition'] = 'attachment;  filename="kar_list.txt"'

    writer = csv.writer(response)

    
    # writer.writerow(['workhouse__Code','workhouse__Name','workhouse__Address',
    #             'year','month','worker_num','days_sum','daily_wage_sum','monthly_wage_sum','monthly_advantage',
    #             'monthly_wage_and_advantage',])
    # users = User.objects.all().values_list('username', 'first_name', 'last_name', 'email')
    
    mon_list =MonthList.objects.all()

    mon_list=mon_list.annotate(worker_num=Count('detailslist'))
    mon_list=mon_list.annotate(days_sum=Sum('detailslist__working_days'))
    mon_list=mon_list.annotate(daily_wage_sum=Sum('detailslist__daily_wage'))
    mon_list=mon_list.annotate(monthly_wage_sum=Sum(ExpressionWrapper(F('detailslist__working_days') * F('detailslist__daily_wage') , output_field=BigIntegerField())))
    mon_list=mon_list.annotate(monthly_advantage=Sum('detailslist__advantage'))  

    mon_list=mon_list.annotate(monthly_wage_and_advantage=Sum(ExpressionWrapper( F('detailslist__advantage') + (F('detailslist__daily_wage') * F('detailslist__working_days')), output_field=BigIntegerField()) )) 
    mon_list=mon_list.annotate(total_wage=Sum(ExpressionWrapper( F('detailslist__advantage') + (F('detailslist__daily_wage') * F('detailslist__working_days')), output_field=BigIntegerField()) )) 

    mon_list=mon_list.annotate(employer_share_sum=ExpressionWrapper(F('total_wage')*0.2,output_field=BigIntegerField()  ))
    mon_list=mon_list.annotate(insured_share_sum=ExpressionWrapper(F('total_wage')*0.07,output_field=BigIntegerField()  ))
    mon_list=mon_list.annotate(unemployment_premium_sum=ExpressionWrapper(F('total_wage')*0.03,output_field=BigIntegerField()  ))
    mon_list=mon_list.annotate(list_number=Value('01', CharField()))
    mon_list=mon_list.annotate(list_type=Value('0', CharField()))
    mon_list=mon_list.annotate(list_description=Value('2', CharField()))
    mon_list=mon_list.annotate(porsantaj_ratio=Value('0', CharField()))
    mon_list=mon_list.annotate(hard_ratio=Value('0', CharField()))


    # mon_list=mon_list.extra(select = {'list_number': 0})
    # mon_list=mon_list.extra(select = {'list_type': 0})
    # mon_list=mon_list.extra(select = {'list_description': ''})
    # mon_list=mon_list.extra(select = {'porsantaj_ratio': 0})
    # mon_list=mon_list.extra(select = {'hard_ratio': 0})

    
    mon=mon_list.values_list('workhouse__Code','workhouse__Name','workhouse__Client','workhouse__Address','list_type',
                'year','month','list_number','list_description','worker_num','days_sum','daily_wage_sum','monthly_wage_sum','monthly_advantage',
                'monthly_wage_and_advantage','total_wage','insured_share_sum','employer_share_sum','unemployment_premium_sum',
                'workhouse__Ratio','porsantaj_ratio','hard_ratio','workhouse__ContractRow',  )

    for m in mon:
        m=list(m)
        m[1]=reverse(m[1])
        m[2]=reverse(m[2])
        m[3]=reverse(m[3])
        m[8]=reverse(m[8])


        writer.writerow(m)   

    
            
    return response



def export_workers_data(request): 

    #this section for .csv files

    response = HttpResponse(content_type='text/csv ;charset=iransystem')
    response['Content-Disposition'] = 'attachment;  filename="work_list.txt"'

    writer = csv.writer(response)
    # writer.writerow(['header names list'])
    workers_list=DetailsList.objects.all()


    workers_list=workers_list.annotate(monthly_wage=(ExpressionWrapper(F('working_days') * F('daily_wage') , output_field=BigIntegerField())))
    workers_list=workers_list.annotate(monthly_wage_and_advantage=(ExpressionWrapper( F('advantage') + (F('daily_wage') * F('working_days')), output_field=BigIntegerField()) )) 
    workers_list=workers_list.annotate(total_wage=(ExpressionWrapper( F('advantage') + (F('daily_wage') * F('working_days')), output_field=BigIntegerField()) )) 
    workers_list=workers_list.annotate(insured_share=ExpressionWrapper(F('total_wage')*.07,output_field=BigIntegerField()  ))
    workers_list=workers_list.annotate(list_number=Value('01', CharField()))
    workers_list=workers_list.annotate(porsantaj_ratio=Value('0', CharField()))
    
   
   
    # workers = workers_list.values_list('month_list__workhouse__Code','month_list__year',
    #                     'month_list__month','list_number','worker__BimehNum','worker__FirstName','worker__LastName',
    #                     'worker__DadName','worker__IdNum','worker__IdPlace','worker__RegisterDate',
    #                     'worker__BirthDate','worker__Sex','worker__Nationality','worker__Job',
    #                     'start_date','end_date','working_days','daily_wage','monthly_wage',
    #                     'advantage','monthly_wage_and_advantage','total_wage','insured_share','porsantaj_ratio',
    #                     'worker__Job','worker__NationNum',)

    #new stracture
    workers = workers_list.values_list('month_list__workhouse__Code','month_list__year',
                        'month_list__month','list_number','worker__BimehNum','worker__FirstName','worker__LastName',
                        'worker__DadName','worker__IdNum','worker__IdPlace','worker__RegisterDate',
                        'worker__Sex','worker__Nationality','worker__Job',
                        'start_date','end_date','working_days','daily_wage','monthly_wage',
                        'advantage','monthly_wage_and_advantage','total_wage','insured_share','porsantaj_ratio',
                        'worker__Job','worker__BirthDate','worker__NationNum',)


    #TODO:advantage is daily or note
    #TODO : diffrence between monthly_wage_and_advantage and total_wage

    sex_chioce_dict={'1':'مرد','2':'زن'}
    job_chioce_dict={code:value for code,value in job_choice}
    nat_chioce_dict={'1':'ايراني','2':'غیر ايراني'}
    city_chioce_dict={code:value for code,value in city_choice}
    for worker in workers:
        worker=list(worker)

        worker[5]=reverse(worker[5])
        worker[6]=reverse(worker[6])
        worker[7]=reverse(worker[7])

        #remove two zero at insuranse code
        worker[4]=worker[4][2:]

        #define sex describ instead of its code
        worker[11]=reverse(sex_chioce_dict[worker[11]]) 

        #define job describ instead of its code
        worker[13]=reverse(job_chioce_dict[worker[13]])

        #define nationality describ instead of its code
        worker[12]=reverse(nat_chioce_dict[worker[12]])

        #define city describ instead of its code
        worker[9]=reverse(city_chioce_dict[worker[9]])
  
        writer.writerow(worker)
    return response


#########################################
    # with open('w.txt', 'w', newline='', encoding='iransystem') as f:
    #     writer = csv.writer(f)
    #     for worker in workers:

                

    #         worker=list(worker)
            
  
    #         #remove two zero at insuranse code
    #         worker[4]=worker[4][2:]

    #         #define sex describ instead of its code
    #         worker[11]=sex_chioce_dict[worker[11]]

    #         #define job describ instead of its code
    #         worker[13]=job_chioce_dict[worker[13]]

    #         #define nationality describ instead of its code
    #         worker[12]=nat_chioce_dict[worker[12]]

    #         #define city describ instead of its code
    #         worker[9]=city_chioce_dict[worker[9]]

    #         w=[]
            
    #         writer.writerow(worker)  


    #         # for i in worker:
    #         #     i=str(i)
    #         #     # i=i.encode('utf-8')
    #         #     # i=i.decode('iransystem')
    #         #     w.append(i)
    #         # worker=w
    #         # writer.writerow(worker)  
    # return response
######################################


def import_workhouses_data(request):
    
    # importing csv module 
    import csv 

    # csv file name 
    filename = "workhouse.csv"

    # initializing the titles and rows list 
    # fields = [] 
    rows = [] 

    # reading csv file 

main/templates/main/_base.html
{% comment %} <!DOCTYPE html>
{% load static %}
<html lang="en" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static "main/css/main.css" %}">
    <title>
        
        {% block title %}

        {% endblock %}
    
    </title>
</head>
<body>
<div class="container" id="container">
    <div class="row align-items-center" id="header">
        <div class="col text-center">
            <h2>
                سامانه تنظیم لیست بیمه
            </h2>
        </div>
    </div>

    <div class="row align-items-center" id="toolbar">

        <div class="col-6">
            <h4>
                <p>sdsd</p>
            </h4>
        </div>



        <a href='/' >صفحه اصلی  </a>
        

    </div>    
    {% block mainContent %}

        {% endblock %}

</div>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<script src="{% static "main/js/main.js" %}"></script>
</body>
</html> {% endcomment %}


<!DOCTYPE html>
{% load static %}

<html lang="en">
<title>
  {% block title %}
            
        

  {% endblock %}
</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<link rel="stylesheet" type="text/css" href="{% static "main/css/main.css" %}">

<body>





<!-- Navbar -->

<nav class="navbar fixed-top navbar-DARK bg-dark">
  <a class="navbar-brand" href='/'>سامانه تنظیم لیست بیمه</a>

  <div class="btn-group">
    <a class="btn btn-secondary dropdown-toggle " href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      اطلاعات پایه
    </a>

    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink" style=' margin:-12px'>
      <a class="dropdown-item" href={% url 'main:workhouses_list' %}>مشخصات کارگاه</a>
      <a class="dropdown-item" href={% url 'main:workers_list' %}>مشخصات کارکنان</a>
      
    </div>
 

  <div class="btn-group">
    <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      عملیات
    </a>

    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink" style=' margin:-12px'>
      <a class="dropdown-item" href={% url 'main:month_list' %}>لیست ماهانه </a>

    </div>
  </div>  

  <div class="btn-group">
    <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      پشتیبانی
    </a>

    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink" style=' margin:-12px'>
      <a class="dropdown-item" href={% url 'main:import_workhouses_data' %}> وارد کردن اطلاعات کارگاه </a>
      <a class="dropdown-item" href={% url 'main:import_workers_data' %}> وارد کردن اطلاعات کارکنان </a>

    </div>
  </div>  



</nav>



<!-- Sidebar -->
{% block sidebar %}
  <nav class="w3-sidebar w3-bar-block w3-collapse w3-large w3-theme-l5 w3-animate-left" id="mySidebar">
    <a href="javascript:void(0)" onclick="w3_close()" class="w3-right w3-xlarge w3-padding-large w3-hover-black w3-hide-large" title="Close Menu">
      <i class="fa fa-remove"></i>
    </a>
    <h4 class="w3-bar-item"><b>منو</b></h4>
    <a class="w3-bar-item w3-button w3-hover-black" href='/' >صفحه اصلی  </a>

  
{% endblock %}
</nav>






<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- Main content: shift it to the right by 250 pixels when the sidebar is visible -->
<div class="w3-main" style="margin-left:250px">

  <div class="w3-row w3-padding-64">
    <div class="w3-twothird w3-container">
      <h1 class="w3-text-teal">
      
            {% block pagetitle %}
            
            

            {% endblock %}</h1>
        
            {% block mainContent %}
            
        

            {% endblock %}
    </div>
    <div class="w3-third w3-container">
      <p class="w3-border w3-padding-large w3-padding-32 w3-center">AD</p>
      <p class="w3-border w3-padding-large w3-padding-64 w3-center">AD</p>
    </div>
  </div>


<!-- Footer -->
<footer class="page-footer font-small bg-dark text-warning pt-4">

  <!-- Footer Links -->
  <div class="container-fluid text-center text-md-left">

    <!-- Grid row -->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-6 mt-md-0 mt-3">

        <!-- Content -->
        <h5 class="text-uppercase">Footer Content</h5>
        <p>Here you can use rows and columns to organize your footer content.</p>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none pb-3">

      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">

        <!-- Links -->
        <h5 class="text-uppercase">Links</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!">Link 1</a>
          </li>
          <li>
            <a href="#!">Link 2</a>
          </li>
          <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">

        <!-- Links -->
        <h5 class="text-uppercase">Links</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!">Link 1</a>
          </li>
          <li>
            <a href="#!">Link 2</a>
          </li>
          <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="https://mdbootstrap.com/"> MDBootstrap.com</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->


  {% comment %} <footer id="myFooter">
    <div class="w3-container w3-theme-l2 w3-padding-32">
      <h4>Footer</h4>
    </div>

    <div class="w3-container w3-theme-l1">
      <p>Powered by <a href="https://www.w3schools.com/w3css/default.asp" target="_blank">w3.css</a></p>
    </div>
  </footer> {% endcomment %}

<!-- END MAIN -->
</div>


<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<script src="{% static "main/js/main.js" %}"></script>

</body>
</html>

main/templates/main/month_list.html
{% extends 'main/_base.html' %}

{% block title %}

لیست ماهانه

{% endblock %}

{% block sidebar %}
{{ block.super }}
  <a class="w3-bar-item w3-button w3-hover-black" href={% url 'main:list_reg' %} > ثبت لیست جدید </a>


{% endblock %}

{% block pagetitle %}
            
    لیست ماهانه  

{% endblock %}


{% block mainContent %}


{% if months_list %}
    <table style="width:100%"  class="table table-hover">
    <tr  class="text-light bg-dark">
        <th> نام کارگاه</th>
        <th>کد کارگاه</th>
        <th>ردیف کارگاه</th>
        <th> سال</th>
        <th> ماه</th>

    </tr>

    {% for month_list in months_list %}
        {% comment %} <ul> 
            <a href={% url 'main:details_list' list_id=month_list.id %} >
            <li>
                {{month_list}}
            </li>
            </a>
        </ul> {% endcomment %}

     
            <tr class='clickable-row' data-href={% url 'main:details_list' list_id=month_list.id %}>
                <td>{{month_list.workhouse.Name}}</td>

                <td>{{month_list.workhouse.Code}}</td>
                <td>{{month_list.workhouse.ContractRow}}</td>
                <td>{{month_list.year}}</td>
                <td>{{month_list.month}}</td>

                
            </tr>
        



    {% endfor %}
    </table>

{% else %}

<h3>
    هیچ رکوردی وجود ندارد
</h3>
{% endif %}

{% endblock %}